package network;

public enum ServerResponse implements Command {
    HANDSHAKE, LOGGED_IN, LOGGED_OUT, CONNECTED, DISCONNECTED, ERROR, GIVE_EXCURSII_LIST, GIVE_SEARCH_LIST, UPDATE_NOTIFICATION, REZERVARE_MADE, REJECT_CONNECTION
}
